from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CODEMAP = ROOT / "docs/CODEMAP.md"
MAJOR_DIRS = [
    "contract2agent/",
    "contract2agent/evaluation/",
    "contract2agent/evaluation/file_reading/",
    "contract2agent/cost_estimate/",
    "contract2agent/patch_preview/",
    "contract2agent/triage/",
    "contract2agent/templates/",
    "docs/",
    "examples/",
    "tests/",
    "scripts/",
]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Report codemap drift or write a draft codemap section."
    )
    parser.add_argument("--out", type=Path, help="Optional draft output path.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the current codemap appears to miss major items.",
    )
    parser.add_argument(
        "--confirm-overwrite",
        action="store_true",
        help="Allow writing over an existing output file. Required for docs/CODEMAP.md.",
    )
    args = parser.parse_args()

    report = build_report()
    drift = find_drift(report)

    if args.out is None:
        print(report.rstrip())
        if drift:
            print("\nDrift warnings:")
            for item in drift:
                print(f"- {item}")
        return 1 if args.check and drift else 0

    if args.out.is_absolute():
        print("Refusing absolute --out path; write codemap drafts inside the repository.")
        return 2
    out = (ROOT / args.out).resolve()
    try:
        out.relative_to(ROOT)
    except ValueError:
        print(f"Refusing --out path outside repository: {args.out}")
        return 2
    if out == CODEMAP.resolve() and not args.confirm_overwrite:
        print("Refusing to overwrite docs/CODEMAP.md without --confirm-overwrite.")
        return 2
    if out.exists() and not args.confirm_overwrite:
        print(f"Refusing to overwrite existing file without --confirm-overwrite: {relative(out)}")
        return 2

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report.rstrip() + "\n", encoding="utf-8")
    print(f"Wrote codemap draft to {relative(out)}")
    return 1 if args.check and drift else 0


def build_report() -> str:
    lines = [
        "# Codemap Draft",
        "",
        "Generated by `python scripts/harness/update_codemap.py`.",
        "This is a draft/report; review before copying into `docs/CODEMAP.md`.",
        "",
        "## Major Directories",
        "",
    ]
    for directory in MAJOR_DIRS:
        path = ROOT / directory
        status = "present" if path.exists() else "missing"
        lines.append(f"- `{directory}`: {status}")

    lines.extend(["", "## Detected CLI Commands", ""])
    commands = detect_cli_commands()
    if commands:
        for command in commands:
            lines.append(f"- `{command}`")
    else:
        lines.append("- No CLI commands detected.")

    lines.extend(["", "## Tracked Test Files", ""])
    for path in list_tracked_tests():
        lines.append(f"- `{path}`")

    return "\n".join(lines) + "\n"


def find_drift(report: str) -> list[str]:
    if not CODEMAP.exists():
        return ["docs/CODEMAP.md is missing"]
    codemap = CODEMAP.read_text(encoding="utf-8")
    warnings: list[str] = []
    for directory in MAJOR_DIRS:
        if directory not in codemap:
            warnings.append(f"CODEMAP does not mention {directory}")
    for command in detect_cli_commands():
        if command not in codemap:
            warnings.append(f"CODEMAP does not mention CLI command {command}")
    if "Generated by `python scripts/harness/update_codemap.py`" in codemap:
        warnings.append("CODEMAP appears to contain an unreviewed generated draft marker")
    return warnings


def detect_cli_commands() -> list[str]:
    commands: set[str] = set()
    for relative in [
        "contract2agent/cli.py",
        "contract2agent/evaluation/file_reading/cli.py",
    ]:
        path = ROOT / relative
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        commands.update(re.findall(r"add_parser\(\"([a-z0-9][a-z0-9_-]*)\"", text))
        commands.update(re.findall(r"@app\.command\(name=\"([a-z0-9][a-z0-9_-]*)\"", text))
    return sorted(commands)


def list_tracked_tests() -> list[str]:
    try:
        completed = subprocess.run(
            ["git", "ls-files", "tests"],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return sorted(path.relative_to(ROOT).as_posix() for path in (ROOT / "tests").glob("test_*.py"))
    return [line for line in completed.stdout.splitlines() if line.endswith(".py")]


def relative(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


if __name__ == "__main__":
    raise SystemExit(main())
